default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

devuser: &devuser
  username: root
  password:

development:
  <<: *default
  database: test154/DB_developmnt
  <<: *devuser

test:
  <<: *default
  database: test154/DB_test
  <<: *devuser

production:
  <<: *default
  database: test154/DB_production
  username: root
  password:
